@startuml example_ref

class Rectangle {
    +getWidth(): int
    +setWidth(int width): void
    +getHeight(): int
    +setHeight(int height): void
    +getArea(): int
}

class Square {
    +getSide(): int
    +setSide(int side): void
    +getArea(): int
}

class SquareTest {
    +testSetWidth_Square(): void
}

class RectangleTest {
    +testSetWidth_Rectangle(): void
}

Rectangle --|> RectangleTest
Square --|> SquareTest

@enduml
